INSERT INTO schools (schoolName, divisionID, districtID) 
VALUES ("American Heritage Charter School", 1, 6),
("Bliss High School", 1, 4),
("Camas County High School", 1, 4),
("Cambridge High School", 1, 3),
("Carey High School", 1, 4),
("Cascade High School", 1, 3),
("Castleford High School", 1, 4),
("Challis High School", 1, 6),
("Clark County High School", 1, 6),
("Coeur du Christ Academy", 1, 1),
("Council High School", 1, 3),
("Culdesac High School", 1, 2),
("Deary High School", 1, 2),
("Garden Valley High School", 1, 3),
("Genesee High School", 1, 2),
("Grace Lutheran High School", 1, 5),
("Hansen High School", 1, 4),
("Highland High School - Craigmont", 1, 2),
("Horseshoe Bend High School", 1, 3),
("Idaho School for the Deaf & the Blind", 1, 4),
("Kootenai High School", 1, 1),
("Leadore High School", 1, 6),
("Mackay High School", 1, 6),
("Meadows Valley High School", 1, 3),
("Midvale High School", 1, 3),
("Mullan High School", 1, 1),
("Nezperce High School", 1, 2),
("North Gem High School", 1, 5),
("Richfield High School", 1, 4),
("Rockland High School", 1, 5),
("Sage International School Middleton", 1, 3),
("Salmon River High School", 1, 3),
("Shoshone-Bannock High School", 1, 5),
("St. John Bosco Academy", 1, 2),
("Taylor's Crossing Public Charter School", 1, 6),
("Timberline High School - Weippe", 1, 2),
("Watersprings School", 1, 6),
("Alturas Preparatory Academy", 2, 6),
("Butte County High School", 2, 6),
("Centennial Baptist School", 2, 3),
("Clark Fork High School", 2, 1),
("Clearwater Valley High School", 2, 2),
("Gem State Adventist Academy", 2, 3),
("Genesis Prep Academy", 2, 1),
("Glenns Ferry High School", 2, 4),
("Grace High School", 2, 5),
("Greenleaf Friends Academy", 2, 3),
("Hagerman High School", 2, 4),
("Idaho City High School", 2, 3),
("Kamiah High School", 2, 2),
("Kendrick High School", 2, 2),
("Lakeside Junior/Senior High School", 2, 1),
("Lapwai High School", 2, 2),
("Liberty Charter High School", 2, 3),
("Lighthouse Christian High School", 2, 4),
("Logos School", 2, 2),
("Murtaugh High School", 2, 4),
("North Idaho Stem Charter Academy", 2, 1),
("Notus High School", 2, 3),
("Oakley High School", 2, 4),
("Potlatch High School", 2, 2),
("Prairie High School", 2, 2),
("Priest River Lamanna High School", 2, 1),
("Raft River High School", 2, 4),
("Rimrock Jr/Sr High School", 2, 3),
("Riverstone International School", 2, 3),
("Sage International School Boise", 2, 3),
("Shoshone High School", 2, 4),
("Troy High School", 2, 2),
("Valley High School", 2, 4),
("Victory Charter High School", 2, 3),
("Wallace High School", 2, 1),
("Wilder High School", 2, 3),
("Xavier Charter School", 2, 4),
("Aberdeen High School", 3, 5),
("Ambrose School", 3, 3),
("Compass Charter High School", 3, 3),
("Dietrich High School", 3, 4),
("Firth High School", 3, 6),
("Grangeville High School", 3, 2),
("Idaho Arts Charter School", 3, 3),
("Kellogg High School", 3, 1),
("Magic Valley High School", 3, 4),
("Malad High School", 3, 5),
("Marsing High School", 3, 3),
("Melba High School", 3, 3),
("Nampa Christian High School", 3, 3),
("New Plymouth High School", 3, 3),
("North Fremont High School", 3, 6),
("North Star Charter School", 3, 3),
("Orofino High School", 3, 2),
("Parma High School", 3, 3),
("Ririe High School", 3, 6),
("Salmon High School", 3, 6),
("Soda Springs High School", 3, 5),
("St Maries High School", 3, 1),
("Sun Valley Community School", 3, 4),
("Vision Charter School", 3, 3),
("Wendell High School", 3, 4),
("West Jefferson High School", 3, 6),
("West Side High School", 3, 5),
("American Falls High School", 4, 5),
("Bonners Ferry High School", 4, 1),
("Buhl High School", 4, 4),
("Coeur d'Alene Charter Academy", 4, 1),
("Cole Valley Christian High School", 4, 3),
("Declo High School", 4, 4),
("Filer High School", 4, 4),
("Fruitland High School", 4, 3),
("Gooding High School", 4, 4),
("Homedale High School", 4, 3),
("Kimberly High School", 4, 4),
("Marsh Valley High School", 4, 5),
("McCall-Donnelly High School", 4, 3),
("Payette High School", 4, 3),
("Snake River High School", 4, 5),
("Sugar-Salem High School", 4, 6),
("Teton High School", 4, 6),
("Timberlake High School", 4, 1),
("Weiser High School", 4, 3),
("Bear Lake High School", 5, 5),
("Bishop Kelly High School", 5, 3),
("Blackfoot High School", 5, 6),
("Bonneville High School", 5, 6),
("Burley High School", 5, 4),
("Century High School", 5, 5),
("Columbia High School", 5, 3),
("Emmett High School", 5, 3),
("Hillcrest High School", 5, 6),
("Idaho Falls High School", 5, 6),
("Jerome High School", 5, 4),
("Lakeland High School", 5, 1),
("Lewiston High School", 5, 2),
("Middleton High School", 5, 3),
("Minico High School", 5, 4),
("Moscow High School", 5, 2),
("Mountain Home High School", 5, 4),
("Pocatello High School", 5, 5),
("Preston High School", 5, 5),
("Renaissance High School", 5, 3),
("Sandpoint High School", 5, 1),
("Shelley High School", 5, 6),
("Skyline High School", 5, 6),
("Skyview High School", 5, 3),
("South Fremont High School", 5, 6),
("Twin Falls High School", 5, 4),
("Vallivue High School", 5, 3),
("Wood River High School", 5, 4),
("Boise High School", 6, 3),
("Borah High School", 6, 3),
("Caldwell High School", 6, 3),
("Canyon Ridge High School", 6, 4),
("Capital High School", 6, 3),
("Centennial High School", 6, 3),
("Coeur d'Alene High School", 6, 1),
("Eagle High School", 6, 3),
("Highland High School - Pocatello", 6, 5),
("Kuna High School", 6, 3),
("Lake City High School", 6, 1),
("Madison High School", 6, 6),
("Meridian High School", 6, 3),
("Mountain View High School", 6, 3),
("Nampa High School", 6, 3),
("Owyhee High School", 6, 3),
("Post Falls High School", 6, 1),
("Ridgevue High School", 6, 3),
("Rigby High School", 6, 6),
("Rocky Mountain High School", 6, 3),
("Thunder Ridge High School", 6, 6),
("Timberline High School - Boise", 6, 3);